//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aukcija
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productID { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string time { get; set; }
        public Nullable<int> bid { get; set; }
        public string customer { get; set; }
    }
}
